### PR TITLE
fix: database alteration yaml

### PR DESCRIPTION
**Pull request by catusax**
## Summary

fixes the database alteration yaml indent and imagePullPolicy value

### CODE REVIEW

**Review by gao-sun — APPROVED** [review]
thanks @wangsijie we should also update the next version

**Comment by wangsijie** [comment]
@catusax There is a tiny lint issue. And would you mind updating the "next" version too?

**Comment by catusax** [comment]
@wangsijie done

**Comment by wangsijie** [comment]
@catusax the lint issue is:
image

**Comment by catusax** [comment]
> @catusax the lint issue is: image

solved the lint issue, pls check again

**Pull request merged**
